version: '3.9'
services:

  analyzer:
    #image: ghcr.io/natrontech/360-noscope-analyzer:latest
    build: ./analyze
    user: '1001'
    # needed for use with mac m1
    platform: "linux/amd64"
    container_name: 360_analyzer
    ports:
      - "8000:8000"
    networks:
      - net
    environment:
      ELASTIC_URI: https://elasticsearch:9200
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: ""
      SECURITY_USERNAME: admin
      SECURITY_PASSWORD: securepassword

  frontend:
    #image: ghcr.io/natrontech/360-noscope-frontend:latest
    build: ./ui
    # needed for use with mac m1
    platform: "linux/amd64"
    container_name: 360_frontend
    ports:
      - "8090:8090"
    volumes:
      - $PWD/pocketbase/pb_data:/app/pocketbase/pb_data
    networks:
      - net

networks:
  net:
    driver_opts:
      com.docker.network.bridge.name: 360_noscope
