apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-elasticsearch-exporter
spec:
  maxHistory: 5
  interval: 5m0s
  chart:
    spec:
      chart: prometheus-elasticsearch-exporter
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: monitoring
      interval: 60m0s
  install:
    remediation:
      # unlimited retries on helm install
      retries: -1
      # do not cleanup if helm install fails
      remediateLastFailure: false
  upgrade:
    remediation:
      # try helm upgrade 2 times
      retries: 2
      # if helm upgrade fails, rollback to last successfull release
      remediateLastFailure: true
  values:
    ## Values: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter/values.yaml
    env:
      ES_USERNAME: elastic
    es:
      all: true
      indices: true
      sslSkipVerify: true
      uri: http://elasticsearch-es-http:9200
    extraEnvSecrets:
      ES_PASSWORD:
        key: elastic
        secret: elasticsearch-es-elastic-user
    prometheusRule:
      enabled: false
    replicaCount: 1
    resources: {}
    serviceMonitor:
      enabled: true
