noscope360:
  elastic:
    host: ${NOSCOPE360_ELASTIC_HOST}
    port: ${NOSCOPE360_ELASTIC_PORT}
    username: ${NOSCOPE360_ELASTIC_USERNAME}
    password: ${NOSCOPE360_ELASTIC_PASSWORD}

spring:
  mvc:
    problemdetails:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui.html

admin:
  security:
    username: ${ADMIN_SECURITY_USERNAME}
    password: ${ADMIN_SECURITY_PASSWORD}

server:
  port: 8080
