apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  #annotations:
  #  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx-external
  rules:
  - host: es.360.natron.cloud
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: elasticsearch-es-http
              port:
                number: 9200
  tls:
    - hosts:
        - "es.360.natron.cloud"