apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: 360-noscpoe
spec:
  version: 8.9.1
  count: 2
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: 360-noscpoe
spec:
  ingressClassName: nginx-external
  rules:
  - host: kibana.360.natron.cloud
    http:
      paths:
      - backend:
          service:
            name: kibana-kb-http
            port:
              number: 5601
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kibana.360.natron.cloud
    secretName: tls-kibana-360-natron-cloud